image: alpine:latest

stages:
  - pages

pages:
  stage: pages
  script:
    - echo "Public folder already in place, skipping build"
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
